# Site settings
title: Mario Pabon / A programmer based in Brooklyn
email: your-email@domain.com
description: > # Programmer based in Brooklyn
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://mariopabon.com" # the base hostname & protocol for your site
link_twitter: https://twitter.com/restlessbit
link_github: https://github.com/restlessbit
link_medium: 'https://medium.com/@restlessbit'
link_npm: 'https://www.npmjs.com/~restlessbit'
link_stackoverflow: 'http://stackoverflow.com/users/4645524/restlessbit'
contact_email: me@mariopabon.com

# Build settings
markdown: kramdown

highlighter: none

kramdown:
  input: GFM
  hard_wrap: false

# Enable pagination
paginate: 10
paginate_path: "/page/:num/"

# Create a collection for projects
collections:
  projects:

# jekyll-assets
assets:
  sources:
    - node_modules
    - _js

gems:
  - jekyll-assets
  - jekyll-paginate
