require('prismjs/prism')
require('prismjs/components/prism-bash')
require('prismjs/components/prism-jsx')
require('prismjs/components/prism-python')
require('prismjs/plugins/line-numbers/prism-line-numbers.min')
